### ISSUE TITLE
[ TrackView ] Création de la structure de l'extension

### ISSUE THREAD

**Issue by raphael-dsc** [jdev-org/mviewer#5]
**Présentation**

En tant que : Développeur

Je souhaite que : Ajouter une nouvelle extension

Afin de pourvoir : Développer les fonctionnalités du TrackView

**Description fonctionnelle**

Il faut créer la structure de l'addon et ajouter l'appel de l'extension dans l'application démo créé en #4 

**Description technique**

Créer un répertoire dans le répertoire demo/addon avec l'ensemble des fichiers nécessaire à la configuration de l'addon

**Comment by pierrejego** [comment]
Comment configurer une extension : https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_extensions.html
