### ISSUE TITLE
[ TrackView ] Intégration du GPX - Track

### ISSUE THREAD

**Issue by raphael-dsc** [jdev-org/mviewer#6]
**Présentation**

En tant que : Administrateur

Je souhaite : Pouvoir  utiliser un tracé provenant d'un fichier au format GPX

Afin d' : Afficher le parcours  d'un fichier 

**Description fonctionnelle**

Le GPX contient 6 couches, des lignes et des points. L'objectif ici c'est d'afficher la couche "track" du fichier  GPX comme une couche distincte de l'application. Les 5 autres types de données ne sont pas utilisées pour l'instant.

**Description technique**

Les GPX doivent être ajouté à l'application par l'addon et donc l'url doit être configurable dans le fichier de configuration. 

Il faut vérifier que la librairie OpenLayer utilisée dans Mviewer permet l'intégration d'un GPX et le choix d'une couche dans celui-ci.

**Comment by pierrejego** [comment]
Tester en bouclant sur l'ensemble des features pour vérifier que nous avons touts les attributs
